### ISSUE TITLE
Unable to require package with modulemap dependencies

### ISSUE THREAD

**Issue by jnordberg** [SwiftXcode/swift-xcode#10]
I'm trying to include a package that has a c target using swift-xcode, it imports the dependencies fine but when building I get the error `Missing required module 'SomeModule'`, where `SomeModule` is a c-target depended on by the package I'm trying to import.

I've setup a minimal example package that reproduces the issue here:

https://github.com/jnordberg/swift-c-package

To reproduce:

  1. Create a new swift-xcode iOS project from the template
  1. Add `.package(url: "https://github.com/jnordberg/swift-c-package.git", .branch("master")),` to Package.swift dependencies
  1. Add the `TestPackage` to the target dependencies
  1. `import TestPackage` somewhere

**Comment by helje5** [comment]
I do support some packages which include C dependencies (including NIO), so that should actually work. I'll have a look.

**Comment by helje5** [comment]
Hm, right, so this has a modmap in `Sources/TestDep/include`. I guess I don't support that specific thing yet. "Regular" C projects and C modmap targets should work fine (e.g. NIO uses a set of those).

Do you have a better example but the `TestDep`? What do you actually use it for?

**Comment by jnordberg** [comment]
I was using it for swift bindings to a c library (libsecp256k1) but after looking at how Apple did their c deps in NIO I found a way to do it without the `module.modulemap`. Would be neat if swift-xcode supported them though :)

**Comment by helje5** [comment]
Agreed, all the features should work! But I guess this is not a No 1 priority right now, but leaving it open :-)

**Comment by emorydunn** [comment]
I've run into the same issue when trying to add a dependency that requires Vapor. I've tried replicating the various build settings from the SPM generated Xcode project but to no avail.

**Comment by helje5** [comment]
Well, so Runtime and in consequence SwiftObjects is affected as well. So I suppose I have to add it ;-)

**Comment by helje5** [comment]
That should be fixed in SwiftXcode 0.7.4. The old version was looking for C modmaps and headers in the package root dir. The new version also checks Pkg/Sources/Pkg/* and Pkg/Sources/Pkg/include/*.h.
