### ISSUE TITLE
Failing on Spaces in path

### ISSUE THREAD

**Issue by ezfe** [SwiftXcode/swift-xcode#2]
When building in Xcode, a call to `basename` fails with "unexpected argument" and, complaining about the part of the path after the space.

I notice that calls to `basename` don't include `"`s around the path.

**Comment by helje5** [comment]
Yeah, can repro. Working on a fix.

**Comment by helje5** [comment]
OK, think I got it right in `0.5.13`, please give it a try:
```shell
brew upgrade swiftxcode/swiftxcode/swift-xcode
```

**Comment by ezfe** [comment]
This issue has been resolved
